# -*- coding: utf-8 -*-
"""Camada_Pagamentos_Trusted.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xDSjJd-jtOvBJaYQOHHOIxN5X5kGjKq7
"""

!pip install pyspark

from google.colab import drive
drive.mount('/content/gdrive')

with open('/content/gdrive/My Drive/Colab Notebooks/testando_mount.txt', 'w') as f:
    f.write('content')

from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("Data Lake") \
    .config('spark.ui.port', '4050') \
    .getOrCreate()

spark

#Importando as Bibliotecas
from pyspark.sql.functions import input_file_name, split, col, lit, regexp_replace
from datetime import datetime, timedelta
from decimal import Decimal

def log():
  return datetime.now().strftime('%Y-%m-%d %H:%M:%S') +' >>>'

log()

"""**Iniciando o processamento da camada Trusted com o arquivo de Pagamentos**"""

# Criar uma tabela temporária para análise
df_pagamento = spark.read.option('header','True').csv('/content/gdrive/MyDrive/PodCartoes/001_raw/tb_pagamentos_20241201_20241202000000.csv')
df_pagamento.createOrReplaceTempView('df_pagamento')

qtd_registros = df_pagamento.count()
print(log(), f'Quantidade de registro: {qtd_registros}')

df_pagamento.printSchema()

df_pagamento.show()

# Definir o esquema da tabela e corrigir os tipos de dados
spark.sql("""
   select
      cast(split(id_pagamento, '-')[2]as bigint) as id_pagamento,
      cast(split(id_fatura, '-')[1] as bigint) AS id_fatura,
      cast(id_cliente as bigint) as data_emissao,
      cast(data_pagamento as date) as data_pagamento,
      cast(valor_pagamento as decimal(15,2)) as valor_pagamento
   from df_pagamento
""").show()

"""**Variáveis de Processamento e Referência
Organizam e estruturam os dados, facilitando consultas, análises e integração com ferramentas de ciência de dados, aumentando a eficiência e a clareza do Data Lake**
"""

dt_proc = datetime.now().strftime('%Y%m%d%H%M%S')

# Adicionar variáveis de processamento e referência
df_pagamento_format = spark.sql(f"""
   select
      cast(split(id_pagamento, '-')[2]as bigint) as id_pagamento,
      cast(split(id_fatura, '-')[1] as bigint) AS id_fatura,
      cast(id_cliente as bigint) as id_cliente,
       "{dt_proc}" as dt_proc,
      substring(replace(data_pagamento,'-',''),1,6) ref,
      cast(data_pagamento as date) as data_pagamento,
      cast(valor_pagamento as decimal(15,2)) as valor_pagamento
   from df_pagamento
""")
df_pagamento_format.createOrReplaceTempView('df_pagamento_format')

df_pagamento_format.printSchema()

"""**Salvando os dados na Camanda Trusted**"""

df_pagamento_format.write.mode('append').partitionBy('ref').parquet('/content/gdrive/MyDrive/PodCartoes/002_trusted/tb_02pagamento')

"""**Carregamento dos dados da pasta controle**"""

df_controle_pagamento = spark.sql(f"""
   select
      'tb_02pagamento' as tb_nome,
      {dt_proc} as dt_proc,
      {qtd_registros} as qtd_registros

""")

df_controle_pagamento.show()

#Salvar os dados na pasta controle do DataLake
df_controle_pagamento.write.mode('append').parquet('/content/gdrive/MyDrive/PodCartoes/005_controle')