# -*- coding: utf-8 -*-
"""Camada_Fatura_Trusted.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UMiHYlKplsW64wlTNyj_dJ-VBOsWASCK
"""

!pip install pyspark

from google.colab import drive
drive.mount('/content/gdrive')

with open('/content/gdrive/My Drive/Colab Notebooks/testando_mount.txt', 'w') as f:
    f.write('content')

from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("Data Lake") \
    .config('spark.ui.port', '4050') \
    .getOrCreate()

spark

#Importando as Bibliotecas
from pyspark.sql.functions import input_file_name, split, col, lit, regexp_replace
from datetime import datetime, timedelta
from decimal import Decimal

#Criar uma função para registrar a data atual
def log():
  return datetime.now().strftime('%Y-%m-%d %H:%M:%S') +' >>>'

log()

"""**Iniciando o processamento da camada Trusted com o arquivo de Faturas**"""

df_fatura = spark.read.option('header','True').csv('/content/gdrive/MyDrive/PodCartoes/001_raw/tb_faturas_20241201_20241202000000.csv')
df_fatura.createOrReplaceTempView('df_fatura')

qtd_registros = df_fatura.count()
print(log(), f'Quantidade de registro: {qtd_registros}')

df_fatura.printSchema()

df_fatura.show()

# Definir o esquema da tabela e corrigir os tipos de dados

spark.sql("""
   select
      cast(split(id_fatura, '-')[1] as bigint) as id_fatura,
      cast(id_cliente as bigint) as id_cliente,
      cast(data_emissao as date) as data_emissao,
      cast(data_vencimento as date) as data_vencimento,
      cast(valor_fatura as decimal(15,2)) as valor_fatura,
      cast(valor_pagamento_minimo as decimal(15,2)) as valor_pagamento_minimo
   from df_fatura
""").show()

"""**Variáveis de Processamento e Referência
Organizam e estruturam os dados, facilitando consultas, análises e integração com ferramentas de ciência de dados, aumentando a eficiência e a clareza do Data Lake**
"""

#Variáveis de processamento e referência
dt_proc = datetime.now().strftime('%Y%m%d%H%M%S')

df_fatura_format = spark.sql(f"""
   select
      cast(split(id_fatura, '-')[1] as bigint) as id_fatura,
      cast(id_cliente as bigint) as id_cliente,
      "{dt_proc}" as dt_proc,
      substring(replace(data_emissao,'-',''),1,6) ref,
      cast(data_emissao as date) as data_emissao,
      cast(data_vencimento as date) as data_vencimento,
      cast(valor_fatura as decimal(15,2)) as valor_fatura,
      cast(valor_pagamento_minimo as decimal(15,2)) as valor_pagamento_minimo
   from df_fatura
""")
df_fatura_format.createOrReplaceTempView('df_fatura_format')

"""**Salvando os dados na Camanda Trusted**"""

df_fatura_format.write.mode('append').partitionBy('ref').parquet('/content/gdrive/MyDrive/PodCartoes/002_trusted/tb_01fatura')

tb_fatura= spark.read.parquet('/content/gdrive/MyDrive/PodCartoes/002_trusted/tb_02pagamento')
tb_fatura.createOrReplaceTempView('tb_fatura')

"""**Carregamento dos dados da pasta controle**"""

#Criar uma pasta de controle do processamento
df_controle_fatura = spark.sql(f"""
   select
      'tb_01fatura' as tb_nome,
      {dt_proc} as dt_proc,
      {qtd_registros} as qtd_registros

""")

df_controle_fatura.write.mode('append').parquet('/content/gdrive/MyDrive/PodCartoes/005_controle')