# -*- coding: utf-8 -*-
"""Book_de_Variaveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Xof1J8v_1CEWI1Hmzqa3JEzw-_HwHYI
"""

!pip install pyspark

from google.colab import drive
drive.mount('/content/gdrive')

from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("Data Lake") \
    .config('spark.ui.port', '4050') \
    .getOrCreate()

spark

"""**Iniciando o Book de Variáveis**"""

#Importando as Bibliotecas
from pyspark.sql.functions import input_file_name, split, col, lit, regexp_replace
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from decimal import Decimal

#Criar uma função log para registrar a data
def log():
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S') +' >>>'
dt_proc = datetime.now().strftime('%Y%m%d%H%M%S')
current_date = datetime.now().strftime('%Y%m%d')

#Variaveis para realizar filtros na camada Trusted, nesse caso o mes de referencia é o final de janeiro/24
dt_proc_book = datetime.strptime('2024-01-31', '%Y-%m-%d')
dt_inicio_proc_book = dt_proc_book - relativedelta(months = 12)

dt_proc_book = dt_proc_book.strftime('%Y%m')
dt_inicio_proc_book = dt_inicio_proc_book.strftime('%Y%m')

dt_proc_book, dt_inicio_proc_book

dt_proc_book_str =datetime.strptime('2024-01-31', '%Y-%m-%d').strftime('%Y-%m-%d')
dt_proc_book_str

"""**Comecando a leitura dos dados da Camada Trusted**"""

tb_fatura= spark.read.parquet('/content/gdrive/MyDrive/PodCartoes/002_trusted/tb_01_fatura')
tb_fatura_00 =tb_fatura.where(f'ref >= {dt_inicio_proc_book} and ref<= {dt_proc_book}')
tb_fatura_00.createOrReplaceTempView('tb_fatura_00')

tb_fatura.count()

tb_fatura.printSchema()

spark.sql("select min(ref) from tb_fatura_00").show()

spark.sql("select max(ref) from tb_fatura_00").show()

"""# Verificação de tratamento se houver de dados duplicados"""

#Verificar se há duplicação nos dados
spark.sql("""
    select
        id_cliente,
        id_fatura,
        count(*)
        from tb_fatura_00
        group by 1,2
        order by 3 desc

""").show()

tb_fatura_00.where('id_cliente = 184 and id_fatura =13 ').show()

tb_fatura_dupli = spark.sql("""
    select
       ref || dt_proc as dedupli_key,
       *
    from tb_fatura_00
""")
tb_fatura_dupli.show()

tb_fatura_dupli = spark.sql("""
    select
       ref || dt_proc as dedupli_key,
       *
    from tb_fatura_00

""")
tb_fatura_dupli.createOrReplaceTempView("tb_fatura_dupli")

#Retornar o valor maximo da deduplicação
tb_fatura_dupli_00 = spark.sql("""
    select
        id_fatura,
        id_cliente,
        max(dedupli_key) as maximo_deduplic
        from tb_fatura_dupli
        group by 1,2

""")
tb_fatura_dupli_00.createOrReplaceTempView("tb_fatura_dupli_00")

tb_fatura_dupli_00.where('id_cliente = 184 and id_fatura =3 ').show()

tb_fatura_dupli_01 = spark.sql("""
     select
     a.*
     from tb_fatura_dupli a
     left join tb_fatura_dupli_00 b
     on a.id_cliente = b.id_cliente and a.id_fatura = b.id_fatura
     where a.dedupli_key = b.maximo_deduplic

""")
tb_fatura_dupli_01.createOrReplaceTempView('tb_fatura_dupli_01')

# TABELA FINAL DEDUPLICADA
tb_fatura_final = spark.sql("""
    select
        a.*
    from tb_fatura_dupli a
    left join tb_fatura_dupli_00 b
    on a.id_cliente = b.id_cliente
    and a.id_fatura = b.id_fatura
    where a.dedupli_key = b.maximo_deduplic
""")

tb_fatura_final.createOrReplaceTempView("tb_fatura_final")

tb_fatura_final.show()

#Conferindo se os dados duplicados foram apagados
tb_fatura_final.where('id_cliente = 184 and id_fatura =3 ').show()

"""# Tratamento de dados duplicados na tabela pagamento"""

tb_pagamentos= spark.read.parquet('/content/gdrive/MyDrive/PodCartoes/002_trusted/tb_02_pagamento')
tb_pagamentos_00 =tb_pagamentos.where(f'ref >= {dt_inicio_proc_book} and ref<= {dt_proc_book}')
tb_pagamentos_00.createOrReplaceTempView('tb_pagamentos_00')

tb_pagamentos_00.count()

tb_pagamentos.printSchema()

tb_pagamentos = spark.sql("""
    select
        id_fatura,
        id_cliente,
        count(*)
        from tb_pagamentos_00
        group by 1,2
        order by 3 desc

""")

tb_pagamentos.show()

tb_pagamento_dupli = spark.sql("""
    select
       ref || dt_proc as dedupli_key,
       *
    from tb_pagamentos_00
""")

tb_pagamento_dupli.show()

tb_pagamento_dupli = spark.sql("""
    select
       ref || dt_proc as dedupli_key,
       *
    from tb_pagamentos_00

""")
tb_pagamento_dupli.createOrReplaceTempView("tb_pagamento_dupli")

tb_pagamento_dupli = spark.sql("""
    select
        id_fatura,
        id_cliente,
        max(dedupli_key) as maximo_deduplic
        from tb_pagamento_dupli
        group by 1,2

""")
tb_pagamento_dupli.createOrReplaceTempView("tb_pagamento_dupli_00")

# TABELA FINAL DEDUPLICADA (mantém todas as colunas)
tb_pagamento_final = spark.sql("""
    select
        a.*
    from tb_pagamento_dupli a
    left join tb_pagamento_dupli_00 b
    on a.id_cliente = b.id_cliente
    and a.id_fatura = b.id_fatura
    where a.dedupli_key = b.maximo_deduplic
""")

tb_pagamento_final.createOrReplaceTempView("tb_pagamento_final")

spark.sql("""
    select
        id_cliente,
        id_fatura,
        count(*)
        from tb_pagamento_final
        group by 1,2
        order by 3 desc

""")

tb_pagamento_final.show()

#Conferindo se os dados duplicados foram apagados
tb_pagamento_final.where('id_cliente = 184 and id_fatura = 3 ').show()

"""**Começar a camada pré-book de variaveis chamada de Stage onde sera criada as classificações e variaveis categoricas **"""

tb_fatura_final.columns

tb_pagamento_final.columns

#unindo as tabelas fatura e pagamento
df_join = spark.sql("""
     select
        a.id_cliente,
        a.id_fatura,
        a.data_emissao,
        a.data_vencimento,
        a.valor_fatura,
        a.valor_pagamento_minimo,
        b.id_pagamento,
        b.data_pagamento,
        b.valor_pagamento
     from tb_fatura_final a
     left join tb_pagamento_final b
     on a.id_fatura = b.id_fatura and a.id_cliente = b.id_cliente
     order by  a.id_cliente, a.id_fatura

""")
df_join.createOrReplaceTempView('df_join')

df_join.show(30)

#criando classificações de variaveis para os dados começando pelos pagamentos

spark.sql("""
     select

          id_cliente,
          id_fatura,
          data_emissao,
          data_vencimento,
          data_pagamento

     from df_join

""").show()

spark.sql("""
     select

          id_cliente,
          id_fatura,
          data_emissao,
          data_vencimento,
          data_pagamento,

            CASE
             when data_pagamento is NULL then 'NAO_PAGO'
             when data_pagamento = data_vencimento then 'PAGO_EM_DIA'
             when data_pagamento < data_vencimento then 'PAGAMENTO_ANTECIPADO'
             When data_pagamento > data_vencimento then 'PAGO_EM_ATRASO'


          end fbc_classificacao_pagamento
     from df_join




""").show()

#verificando os dados nulos se estao corretos
df_join.where('id_cliente = 1 and id_fatura = 6').show() # NAO PAGO

df_join.where('id_cliente = 2 and id_fatura = 7').show() # PAGO_EM_ATRASO

df_join.where('id_cliente = 3 and id_fatura = 2').show() # PAGAMENTO_ANTECIPADO

tb_classificacao_pagamento = spark.sql("""
     select
         *,
            CASE
             when data_pagamento is NULL then 'NAO_PAGO'
             when data_pagamento = data_vencimento then 'PAGO_EM_DIA'
             when data_pagamento < data_vencimento then 'PAGAMENTO_ANTECIPADO'
             When data_pagamento > data_vencimento then 'PAGO_EM_ATRASO'


          end fbc_classificacao_pagamento
     from df_join

""")
tb_classificacao_pagamento.createOrReplaceTempView('tb_classificacao_pagamento')

tb_classificacao_pagamento.show()

tb_dias_atraso = spark.sql(f"""
     select
       *,

            CASE
             when  fbc_classificacao_pagamento = 'NAO_PAGO' then datediff('{dt_proc_book_str}',data_vencimento)
             when  fbc_classificacao_pagamento = 'PAGO_EM_ATRASO' then datediff(data_pagamento,data_vencimento)
             when  fbc_classificacao_pagamento = 'PAGO_EM_DIA' then 0
             when  fbc_classificacao_pagamento = 'PAGAMENTO_ANTECIPADO' then 1

          end fvl_numero_dias_atraso

     from tb_classificacao_pagamento



""")
tb_dias_atraso.createOrReplaceTempView('tb_dias_atraso')

tb_dias_atraso.show()

tb_dias_atraso.columns

#criando a tabela para salvar na camada refined na estapa de pre-book e com variaveis para contar o numero de transacoes
stage= spark.sql(f"""
     select
        id_cliente,
        substring(replace('{dt_proc_book_str}', '-',''),1,6)as ref,
        "{dt_proc}" as dt_proc,

        fbc_classificacao_pagamento,
        data_emissao,

        valor_fatura as fvl_valor_fatura,
        fvl_numero_dias_atraso,
        1 as fvl_qtd_transacoes
      from tb_dias_atraso


""")
stage.createOrReplaceTempView('stage')

stage.show()

"""**Salvando a tabela  stage  na camada Refine**"""

stage.write.mode('append').partitionBy('ref').parquet('/content/gdrive/MyDrive/PodCartoes/Refined/Stage/stage_fatura')

"""**Book de Variaveis**"""

#Começando o book de variaveis atraves da emissao na janela de tempo 1m, 3m, 6m, 12m
spark.sql(f"""
      select
      '{dt_proc_book_str}',
       data_emissao,
       months_between("{dt_proc_book_str}",data_emissao),
      (case when months_between("{dt_proc_book_str}",data_emissao) <= 1 then 1 else  0 end) flg_u1m,
      (case when months_between("{dt_proc_book_str}",data_emissao) <= 3 then 1 else  0 end) flg_u3m,
      (case when months_between("{dt_proc_book_str}",data_emissao) <= 6 then 1 else  0 end) flg_u6m,
      (case when months_between("{dt_proc_book_str}",data_emissao) <= 12 then 1 else 0 end) flg_u12m

     from stage


""").show()

janela_de_tempo = spark.sql(f"""
      select
      *,

       months_between("{dt_proc_book_str}",data_emissao),
      (case when months_between("{dt_proc_book_str}",data_emissao) <= 1 then 1 else  0 end) flg_u1m,
      (case when months_between("{dt_proc_book_str}",data_emissao) <= 3 then 1 else  0 end) flg_u3m,
      (case when months_between("{dt_proc_book_str}",data_emissao) <= 6 then 1 else  0 end) flg_u6m,
      (case when months_between("{dt_proc_book_str}",data_emissao) <= 12 then 1 else 0 end) flg_u12m

     from stage


""")
janela_de_tempo.createOrReplaceTempView('janela_de_tempo')

spark.sql(""" select fbc_classificacao_pagamento from janela_de_tempo group by 1 """).show()

# Criando as combinações da agregação e da janela de tempo
fbcs = ['PAGO_EM_ATRASO', 'NAO_PAGO', 'PAGO_EM_DIA', 'PAGAMENTO_ANTECIPADO']
fvls = ['FVL_VALOR_FATURA', 'FVL_QTD_TRANSACOES', 'FVL_NUMERO_DIAS_ATRASO']
janelas = ['1', 'FLG_U1M', 'FLG_U3M', 'FLG_U6M', 'FLG_U12M']
aggs = ['SUM', 'AVG', 'MIN', 'MAX']
count = 1

# Inicia a construção da consulta SQL
sql_query = """
SELECT
    id_cliente,
    ref,
"""


for fbc in fbcs:
    for fvl in fvls:
        for janela in janelas:
            for agg in aggs:

                if (fvl == 'FVL_NUMERO_DIAS_ATRASO' and agg == 'SUM') or (fvl == 'FVL_QTD_TRANSACOES' and agg != 'SUM'):
                    continue
                else:
                    sql_query += f'    {agg}(CASE WHEN FBC_CLASSIFICACAO_PAGAMENTO = "{fbc}" AND {janela} = 1 THEN {fvl} END) AS VAR_{count},\n'
                    count += 1

sql_query = sql_query.rstrip(",\n") + "\n"


sql_query += """
FROM janela_de_tempo
GROUP BY 1, 2
"""


print(sql_query)

book1 =sql_query

book = spark.sql(book1)
book.show(1)

#consultando os dados do id_cliente = 127 e verificando se os valores bateram
janela_de_tempo.where('id_cliente = 127 ').show()

"""**Salvando o Book na camda Refined**"""

book.write.mode('append').partitionBy('ref').parquet('/content/gdrive/MyDrive/PodCartoes/Refined/book_fatura')